### ISSUE TITLE
Performance when handling "User leave the room"

### ISSUE THREAD

**Issue by Puskin2911** [Puskin2911/SE04-Group-23.1#2]
- When a user leaves the room. We have to remove he/she from the room which he/she is in it. 

- We must be acquire `roomId`. This can be achieved in 2 ways:

1. Get `roomId` in request from client.
2. Find room where user is in. 

==> Which way would be better ?
** More info: For now, we store all room in a `ArrayList`.
@dang007x @Hokage-Itachi : Give me a solution, please!

**Comment by thanhcute123** [comment]
1. Currently, We store all room in a ArrayList. This mean, when you have a roomId, We have to browse the list to find the room. 
Therefore, retrieving the roomId from the client is not necessary
2. In the near future, when the number of rooms becomes larger. We need another solution. So we don't need to be too concerned with the current implementation.

**Comment by Puskin2911** [comment]
Ok, that's good.
