### ISSUE TITLE
External configuration in Spring Boot

### ISSUE THREAD

**Issue by bichphuonggb** [Puskin2911/SE04-Group-23.1#22]
- Spring Boot allow external configuration in some way.
- We need to know about external configuration in Spring boot to customize some thing we need to run application.
- All also need a documentation about this.
- @Puskin2911 i Think you good at this problem. Can you do that ?

**Comment by Puskin2911** [comment]
Ok, I will take care this.

**Comment by Puskin2911** [comment]
I have completed this task, you can find it in the wiki page or right [here](https://github.com/Puskin2911/SE04-Group-23.1/wiki/Spring-Boot:-Load-External-Configuration)
