### ISSUE TITLE
Canvas with React

### ISSUE THREAD

**Issue by dang007x** [Puskin2911/SE04-Group-23.1#23]
- We need to manage the state of a canvas element in React element. 
- I think, this issue is only for me, I will take care this. But, it is good infomation for you guys, @Puskin2911, @Hokage-Itachi , @thanhcute123 , @bichphuonggb1006

**Comment by Puskin2911** [comment]
- Ok, I just assigned this task for you @dang007x .
- And one more requirement for this task, If you can, write a documentation about this problem, please.
- I also have an documentation about using Canvas via JavaScript. Then you can see it when you need. 👍

**Comment by Puskin2911** [comment]
I'm sorry, my documentation is [here](https://github.com/Puskin2911/SE04-Group-23.1/wiki/Draw-graphics-via-JavaScript-with-Canvas).
