### ISSUE TITLE
Understand binding in JavaScript and using arrow function in ReactJs

### ISSUE THREAD

**Issue by Puskin2911** [Puskin2911/SE04-Group-23.1#24]
- In JavaScript, there are some thing will make confuse for beginner. That may be:
   - The `this` keyword
   - binding method
   - The __arrow function__
   - And so on....
- We need to clarify all of those to get better for learning and coding.
- @thanhcute123 @bichphuonggb1006 . I thing you have to write a documentation about this problem. This helps you to re-learn your knowledge

**Comment by Puskin2911** [comment]
And @dang007x . I think you can help @thanhcute123  and @bichphuonggb1006  to complete this documentation!

**Comment by dang007x** [comment]
Yeah, I can help her.

**Comment by thanhcute123** [comment]
thanks you so much.
