### ISSUE TITLE
React router

### ISSUE THREAD

**Issue by dang007x** [Puskin2911/SE04-Group-23.1#25]
- React Router, and dynamic, client-side routing, allows us to build a single-page web application with navigation without the page refreshing as the user navigates. React Router uses component structure to call components, which display the appropriate information.
- By preventing a page refresh, and using Router or Link, the flash of a white screen or blank page is prevented. This is one increasingly common way of having a more seamless user experience. React router also allows the user to utilize browser functionality like the back button and the refresh page while maintaining the correct view of the application.

- To improve user experience of our application. I think we can use `React Router` for our application.

> @Hokage-Itachi you can handle that?
**Note**: You do not need to learn all thing about `React Router`, just basic things, enough for our application.

**Comment by Hokage-Itachi** [comment]
I dont thing I can handle that.

**Comment by Puskin2911** [comment]
Don't worry. I will take care that!
