### ISSUE TITLE
Server store jwt token instead of client store

### ISSUE THREAD

**Issue by Puskin2911** [Puskin2911/SE04-Group-23.1#28]
- Today, I'm so tired of catching a cold. But I learned a lot of new knowledge about authentication chain.
- The first thing, I try to implement a router, which handle all route of our application. I created public route and private route and implement authenticate at React level. At this point, I was confused about token storage. I have 3 solution:
  - Local Storage store (1)
  - Cookie Storage store (2)
  - React context store (3) 
- A lot of articles discuss about first and second solution. All of this is not good choice for security problem. Because of this, i try to implement a context in React at top-level component to store token. I caught a new problem: context was disappeared when user refresh page.
- Then, I found another mechanism for user authentication is token will be store at server instead of client. In detail:
  - For `POST` request `\api\auth\login`. We don't response token. Instead of, we add the token to `HTTPOnly` cookie in header.
  - Then, server need to produce a new api called health check, which validate token for every use.
  - At React-level, for all private resource, we need to call health check api first to validate token:
    - If token is valid, render this page.
    - Other wise, Redirect to login page.
  - **Note**: For every request to server, we need to include cookie, which have token inside.
- Actually, We not need to follow this approach. But i'm try to implement best practices for our application. Try to learn new things, try my best
- How you think about this problem, all friends: @dang007x , @Hokage-Itachi @thanhcute123 , @bichphuonggb1006

**Comment by thanhcute123** [comment]
@Puskin2911 I think you are doing well, but take care of yourself.

**Comment by bichphuonggb** [comment]
In my opinion, all 3 solutions you give are good solutions. I think you should also learn more about the first two solutions. You are doing well. Remember to take care of your health !!!

**Comment by Hokage-Itachi** [comment]
I think you should choose solution 2, that only one I know. That's my opinion. you should choose the solution you think easiest. And take care of yourself...

**Comment by Puskin2911** [comment]
- Lol, my all friends. I tried to implements _server response token in HttpOnly cookie_ . I just added Pull Request about this. You can check it. 
- I think at now, our code maybe have some bugs. But we can fix it later.
- Btw, Thanks for reminder. I will pay more attention to my health!
