### ISSUE TITLE
Handling Thread-safety in RoomUtils class

### ISSUE THREAD

**Issue by thanhcute123** [Puskin2911/SE04-Group-23.1#5]
- Java is Multithreading. 
- Current implementation in `RoomUtils` is not thread-safe.
- We need a thread-safe implementation, other wise, Our application will not function properly . 

===>Hey Guys, Who can do this task ?

@Puskin2911 @dang007x @Hokage-Itachi @bichphuonggb1006

**Comment by Puskin2911** [comment]
Oke, I see. But I think the current implement for `RoomUtils` is not good practices. I think we should make it is `Singleton component` is managed by Spring. I will implement this task. Of course in threaf-safety

**Comment by Puskin2911** [comment]
I done this task. very interested with thread-safe in Java.
