### ISSUE TITLE
Document for final report

### ISSUE THREAD

**Issue by Puskin2911** [Puskin2911/SE04-Group-23.1#60]

**Comment by Puskin2911** [comment]
- To prepare for our final report. We need some documentation about our project. 
- Can you do it for me @Hokage-Itachi  @bichphuonggb1006 
- I already have some something in wiki page for this, you can see it.

**Comment by Hokage-Itachi** [comment]
can you give me outline of this document...??

**Comment by Puskin2911** [comment]
I just update for you. You can quick find here [https://github.com/Puskin2911/SE04-Group-23.1](url)

**Comment by thanhcute123** [comment]
I can support them @Puskin2911

**Comment by bichphuonggb** [comment]
Ok I can do @Puskin2911, and I will help @Hokage-Itachi do it.

**Comment by Hokage-Itachi** [comment]
README  is ok, @Puskin2911????

**Comment by Puskin2911** [comment]
I think it is ok.  Maybe need a little update
