### ISSUE TITLE
Handle Signal Game 

### ISSUE THREAD

**Issue by Puskin2911** [Puskin2911/SE04-Group-23.1#70]
Hey guys. I just reject one Pull Request of @Hokage-Itachi (An Nguyen) about handle signal stop game. This task is not easy for him, and now we need have a lot of discuss about this task.
- The first estimate: I think we have 4 signal in game(4 signal not easy to implement)
  - User leave room when the game is playing
  - User just lose one game
  - User send Surrender Request
  - User send Draw Request
- Can you all give me some idea or solution ?

**Comment by Puskin2911** [comment]
@dang007x @Hokage-Itachi @thanhcute123 @bichphuonggb1006

**Comment by Hokage-Itachi** [comment]
First signal: we need to handle 2 case:
   1. User click out room. This case, I think we simply send a request to server to tell it that the user has out room and game is over.
   2. User disconnect from browser. This case I have not solution yet.

**Comment by Hokage-Itachi** [comment]
Second signal: when user send move to server. Server will check that move. If that move is checkmate, server will response a message that the game is over, who is winner, loser...

**Comment by Puskin2911** [comment]
- The first case is good @Hokage-Itachi . 
- The second case: I think we not need to handle anything. If we can, we must to handle flowing scenario:
  - The server have to have something like clock to count time when one game is playing
  -  user re-connect to server,  if still have time, we need to let user keep to playing this game. Other wise, the rest of player will win. 
  ===> But i think this should be one feature . And it not easy for now.

**Comment by Hokage-Itachi** [comment]
yep.....that's the good solution.....

**Comment by Hokage-Itachi** [comment]
I think the third and fourth signal is the same the first case of the first signal. We just send a request....

**Comment by Hokage-Itachi** [comment]
That's all my solution to this task....

**Comment by thanhcute123** [comment]
Nếu người chơi gửi yêu cầu xin hòa. Thì phải gửi message cho đối thủ biết xem có đồng ý không. Sau đó thì phản hồi kết quả cho mọi người...

**Comment by Puskin2911** [comment]
I also think like you @thanhcute123

**Comment by Puskin2911** [comment]
All is done. Then I closed this topic
