### ISSUE TITLE
Elo for player

### ISSUE THREAD

**Issue by Puskin2911** [Puskin2911/SE04-Group-23.1#72]
- I implemented player have 1200 elo is default . But when one game is over. We need one strategy to calculate elo for player?
- Any idea for me ?

**Comment by Hokage-Itachi** [comment]
I think we just +15 for winner and -15 for loser....

**Comment by Puskin2911** [comment]
- The first: I think +-15 is too much. It can be 12
- The second: Can we have one better strategy? How about a guy with higher elo playing game with one guy who have low elo

**Comment by thanhcute123** [comment]
Các bạn có thể tham khảo cách tính này nhé..

Cách thức tính điểm Elo
1. Công thức toán học của phương pháp Elo & cách áp dụng chung cho toàn game cờ
Giả thiết, bàn cờ 2 đối thủ A & B thi đấu với nhau, trong đó:

Kỳ thủ A có điểm số Elo: Ra
Kỳ thủ B có điểm số Elo: Rb
2. Công thức áp dụng tính điểm:
Công thức (1) – tính cho người chơi A: Ea=Qa/(Qa+Qb)
Công thức (2) – tính cho người chơi B: Eb=Qb/(Qa+Qb)
trong đó:

Qa=10^(Ra/400)
Qb= 10^(Rb/400)
Chú ý: Ea + Eb = 1

3. Điểm trận đấu của kỳ thủ:
Khi hết ván

Thắng: được 1 điểm
Hòa: được 0.5 điểm
Thua: được 0 điểm
4. Công thức điều chỉnh Elo được tính lại sau khi kết thúc mỗi ván đấu, như sau:
Người A: Ra’ = Ra + K(Aa – Ea)
Người B: Rb’ = Rb + K(Ab – Eb)
Trong đó Aa và Ab lần lượt là điểm trận đấu của hai kỳ thủ và K là một hệ số có tác dụng kiểm soát hiện tượng lạm phát và giảm phát. Hệ số K:

K = 25 dành cho kỳ thủ mới có cường số dưới 1600
K = 20 dành cho kỳ thủ mới có cường số dưới 2000
K = 15 dành cho kỳ thủ có cường số dưới 2400.
K = 10 dành cho kỳ thủ có cường số trên 2400
5. Ví dụ để các bạn hiểu hơn nhé:
Giả sử số điểm của kỳ thủ A là 1613, của kỳ thủ B là 1609. Áp dụng công thức (1) và (2), có:

Ea = 0.506
Eb = 0.494.
Giả sử cả hai người đều có hệ số K là 25 và kỳ thủ A bị thua kỳ thủ B.
Điểm trận đấu của A là 0 còn của B là 1. Số điểm mới của hai người sẽ là:

Ra’ = 1613 + 25(0 – 0.506) = 1600
Rb’ = 1609 + 25(1 – 0.494) = 1621

**Comment by Puskin2911** [comment]
Awesome @thanhcute123 . This is very useful. Thank you so muck!

**Comment by Puskin2911** [comment]
@thanhcute123 just provide the solution for this problem. I think I can assign this task for you @Hokage-Itachi  and @dang007x 
Can you all handle this ?

**Comment by dang007x** [comment]
Ok, baby. We could handle this.

**Comment by Puskin2911** [comment]
Done
