### ISSUE TITLE
Bug General checking General

### ISSUE THREAD

**Issue by Puskin2911** [Puskin2911/SE04-Group-23.1#73]
- Hey guys, I just got the funny when i test the game. The case move of General is out of expected.
- Now general can't check general
- Lol, Can you handle this bug, @bichphuonggb1006

**Comment by thanhcute123** [comment]
I think she can. If she needs help, please contact me @bichphuonggb1006

**Comment by bichphuonggb** [comment]
This is easy, I need a little time to do!

**Comment by bichphuonggb** [comment]
tôi đã xử lý lỗi xong rồi nha @Puskin2911
