### ISSUE TITLE
Web UI improvement

### ISSUE THREAD

**Issue by Puskin2911** [Puskin2911/SE04-Group-23.1#75]
- Hi all, The current web UI is pretty bad. We need certain improvements
  - Lobby : background, image, ...
  - Room : background, playing game area, ...

**Comment by Puskin2911** [comment]
@Hokage-Itachi  An Nguyen, Can you care about this problem ?

**Comment by Hokage-Itachi** [comment]
I'm done..

**Comment by Puskin2911** [comment]
Good chop An. But We have something else. As I see, Phuong and Thanh also updated. Good chop all guys
